// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoTAWjXV_oOk2w9hg9m55jBtEyx33d7dA',
    appId: '1:274860410255:web:2a5c0a311df967f2ff37fa',
    messagingSenderId: '274860410255',
    projectId: 'whatsup-backend-f3ca0',
    authDomain: 'whatsup-backend-f3ca0.firebaseapp.com',
    storageBucket: 'whatsup-backend-f3ca0.appspot.com',
    measurementId: 'G-H783VVPW30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmXQmvqabdf9MnHILBjXEBtqbdPMrS4YA',
    appId: '1:274860410255:android:5e08f9da87c30b97ff37fa',
    messagingSenderId: '274860410255',
    projectId: 'whatsup-backend-f3ca0',
    storageBucket: 'whatsup-backend-f3ca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoyK9TlTmzK1Ymt_m8UigTt_enWwmKZmE',
    appId: '1:274860410255:ios:e31d2e7ff8a4db88ff37fa',
    messagingSenderId: '274860410255',
    projectId: 'whatsup-backend-f3ca0',
    storageBucket: 'whatsup-backend-f3ca0.appspot.com',
    iosClientId: '274860410255-vv7qct053psatqm0cp6d944opbblv6eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoyK9TlTmzK1Ymt_m8UigTt_enWwmKZmE',
    appId: '1:274860410255:ios:e31d2e7ff8a4db88ff37fa',
    messagingSenderId: '274860410255',
    projectId: 'whatsup-backend-f3ca0',
    storageBucket: 'whatsup-backend-f3ca0.appspot.com',
    iosClientId: '274860410255-vv7qct053psatqm0cp6d944opbblv6eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsup',
  );
}
